package com.asp4rever.ticketbuyer;

import javax.swing.*;

public class Gui extends javax.swing.JFrame {

    /**
     * Creates new form НовыйJFrame
     */
    public Gui() {
        initComponents();
        initUserComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabelFrom = new javax.swing.JLabel();
        fromField = new javax.swing.JTextField();
        jLabelTill = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        changeButton = new javax.swing.JButton();
        tillField = new javax.swing.JTextField();
        dayBox = new javax.swing.JComboBox<>();
        monthBox = new javax.swing.JComboBox<>();
        dateLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        numTrainLabel = new javax.swing.JLabel();
        anyTrainButton = new javax.swing.JRadioButton();
        specifyTrainButton = new javax.swing.JRadioButton();
        trainNumberField = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        wagonType = new javax.swing.JLabel();
        plazkartButton = new javax.swing.JRadioButton();
        cupeButton = new javax.swing.JRadioButton();
        luxButton = new javax.swing.JRadioButton();
        startButton = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jSeparator7 = new javax.swing.JSeparator();
        authorizeBox = new javax.swing.JCheckBox();
        usernameField = new javax.swing.JTextField();
        loginLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        passenger1 = new javax.swing.JCheckBox();
        surName1 = new javax.swing.JTextField();
        name1 = new javax.swing.JTextField();
        passenger2 = new javax.swing.JCheckBox();
        surName2 = new javax.swing.JTextField();
        name2 = new javax.swing.JTextField();
        childBox2 = new javax.swing.JCheckBox();
        passenger3 = new javax.swing.JCheckBox();
        surName3 = new javax.swing.JTextField();
        name3 = new javax.swing.JTextField();
        childBox3 = new javax.swing.JCheckBox();
        passenger4 = new javax.swing.JCheckBox();
        surName4 = new javax.swing.JTextField();
        name4 = new javax.swing.JTextField();
        childBox4 = new javax.swing.JCheckBox();
        passenger5 = new javax.swing.JCheckBox();
        surName5 = new javax.swing.JTextField();
        name5 = new javax.swing.JTextField();
        childBox5 = new javax.swing.JCheckBox();
        passenger6 = new javax.swing.JCheckBox();
        surName6 = new javax.swing.JTextField();
        name6 = new javax.swing.JTextField();
        childBox6 = new javax.swing.JCheckBox();
        jSeparator5 = new javax.swing.JSeparator();
        lowSeatBox1 = new javax.swing.JCheckBox();
        lowSeatBox2 = new javax.swing.JCheckBox();
        lowSeatBox3 = new javax.swing.JCheckBox();
        lowSeatBox4 = new javax.swing.JCheckBox();
        lowSeatBox5 = new javax.swing.JCheckBox();
        lowSeatBox6 = new javax.swing.JCheckBox();
        allIn1Box = new javax.swing.JCheckBox();
        lateralDisableBox = new javax.swing.JCheckBox();
        cupePriorityBox = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        groupBox1 = new javax.swing.JTextField();
        groupBox2 = new javax.swing.JTextField();
        groupBox3 = new javax.swing.JTextField();
        groupBox4 = new javax.swing.JTextField();
        groupBox5 = new javax.swing.JTextField();
        groupBox6 = new javax.swing.JTextField();
        childBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ticket Buyer 1.0 by Zloj_Pes");
        setIconImages(null);
        setResizable(false);

        jLabelFrom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelFrom.setText("Откуда");

        fromField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fromField.setText("Харьков");
        fromField.setToolTipText("Откуда");
        fromField.setName("test"); // NOI18N
        fromField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldFocusGained(evt);
            }
        });

        jLabelTill.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTill.setText("Куда");

        changeButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        changeButton.setText("Поменять");
        changeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeButtonActionPerformed(evt);
            }
        });

        tillField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tillField.setText("Одесса");
        tillField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldFocusGained(evt);
            }
        });

        dayBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"---", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31"}));

        monthBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"---", "Январь", "Февраль", "Март", "Апрель", "Май", "Июнь", "Июль", "Август", "Сентябрь", "Октябрь", "Ноябрь", "Декабрь"}));

        dateLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dateLabel.setText("Дата отправления:");

        numTrainLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numTrainLabel.setText("Номер поезда:");

        buttonGroup1.add(anyTrainButton);
        anyTrainButton.setText("Любой");
        anyTrainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anyTrainButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(specifyTrainButton);
        specifyTrainButton.setSelected(true);
        specifyTrainButton.setText("Задать");
        specifyTrainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specifyTrainButtonActionPerformed(evt);
            }
        });

        trainNumberField.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        trainNumberField.setForeground(new java.awt.Color(255, 0, 0));
        trainNumberField.setText("059");
        trainNumberField.setToolTipText("Номер поезда");

        wagonType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        wagonType.setText("Тип вагона:");

        buttonGroup2.add(plazkartButton);
        plazkartButton.setSelected(true);
        plazkartButton.setText("Плацкарт");
        plazkartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plazkartButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(cupeButton);
        cupeButton.setText("Купе");
        cupeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cupeButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(luxButton);
        luxButton.setText("Люкс");
        luxButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luxButtonActionPerformed(evt);
            }
        });

        startButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        authorizeBox.setText("Аутентификация на uz.gov.ua");

        usernameField.setText("asp4rever@gmail.com");

        loginLabel.setText("User name");

        passwordLabel.setText("Password");

        passwordField.setText("zdthnsebjg1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(109, 109, 109))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(authorizeBox)
                                                .addGap(84, 84, 84))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jSeparator3)
                                        .addComponent(jSeparator6)
                                        .addComponent(jSeparator1)
                                        .addComponent(jSeparator2)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(numTrainLabel)
                                                .addGap(18, 18, 18)
                                                .addComponent(anyTrainButton)
                                                .addGap(18, 18, 18)
                                                .addComponent(specifyTrainButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(trainNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(wagonType)
                                                .addGap(18, 18, 18)
                                                .addComponent(plazkartButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cupeButton)
                                                .addGap(28, 28, 28)
                                                .addComponent(luxButton))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(dateLabel)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(dayBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(monthBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(jLabelFrom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(jLabelTill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                .addGap(26, 26, 26)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(fromField, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                                                        .addComponent(tillField))
                                                                .addGap(18, 18, 18)
                                                                .addComponent(changeButton)))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(loginLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(passwordLabel)
                                .addGap(69, 69, 69))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabelFrom)
                                                        .addComponent(fromField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabelTill)
                                                        .addComponent(tillField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(changeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(dateLabel)
                                        .addComponent(dayBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(monthBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(numTrainLabel)
                                        .addComponent(anyTrainButton)
                                        .addComponent(specifyTrainButton)
                                        .addComponent(trainNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(wagonType)
                                                .addComponent(plazkartButton))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(cupeButton)
                                                .addComponent(luxButton)))
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(authorizeBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(loginLabel)
                                        .addComponent(passwordLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(startButton)
                                .addContainerGap())
        );

        fromField.getAccessibleContext().setAccessibleName("field");
        fromField.getAccessibleContext().setAccessibleDescription("test");

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Данные пассажиров:");

        passenger1.setSelected(true);
        passenger1.setEnabled(false);

        surName1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        surName1.setText("Фамилия");
        surName1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldFocusGained(evt);
            }
        });

        name1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name1.setText("Имя");
        name1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldFocusGained(evt);
            }
        });

        passenger2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passenger2ActionPerformed(evt);
            }
        });

        surName2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        surName2.setText("Фамилия");
        surName2.setEnabled(false);
        surName2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldFocusGained(evt);
            }
        });

        name2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name2.setText("Имя");
        name2.setEnabled(false);
        name2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldFocusGained(evt);
            }
        });

        childBox2.setText("Детский");
        childBox2.setEnabled(false);

        passenger3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passenger3ActionPerformed(evt);
            }
        });

        surName3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        surName3.setText("Фамилия");
        surName3.setEnabled(false);
        surName3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldFocusGained(evt);
            }
        });

        name3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name3.setText("Имя");
        name3.setEnabled(false);
        name3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldFocusGained(evt);
            }
        });

        childBox3.setText("Детский");
        childBox3.setEnabled(false);

        passenger4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passenger4ActionPerformed(evt);
            }
        });

        surName4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        surName4.setText("Фамилия");
        surName4.setEnabled(false);
        surName4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldFocusGained(evt);
            }
        });

        name4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name4.setText("Имя");
        name4.setEnabled(false);
        name4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldFocusGained(evt);
            }
        });

        childBox4.setText("Детский");
        childBox4.setEnabled(false);

        passenger5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passenger5ActionPerformed(evt);
            }
        });

        surName5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        surName5.setText("Фамилия");
        surName5.setEnabled(false);
        surName5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldFocusGained(evt);
            }
        });

        name5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name5.setText("Имя");
        name5.setEnabled(false);
        name5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldFocusGained(evt);
            }
        });

        childBox5.setText("Детский");
        childBox5.setEnabled(false);

        passenger6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passenger6ActionPerformed(evt);
            }
        });

        surName6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        surName6.setText("Фамилия");
        surName6.setEnabled(false);
        surName6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldFocusGained(evt);
            }
        });

        name6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name6.setText("Имя");
        name6.setEnabled(false);
        name6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldFocusGained(evt);
            }
        });

        childBox6.setText("Детский");
        childBox6.setEnabled(false);

        lowSeatBox1.setText("Только нижнее");

        lowSeatBox2.setText("Только нижнее");
        lowSeatBox2.setEnabled(false);

        lowSeatBox3.setText("Только нижнее");
        lowSeatBox3.setEnabled(false);

        lowSeatBox4.setText("Только нижнее");
        lowSeatBox4.setEnabled(false);

        lowSeatBox5.setText("Только нижнее");
        lowSeatBox5.setEnabled(false);

        lowSeatBox6.setText("Только нижнее");
        lowSeatBox6.setEnabled(false);

        allIn1Box.setSelected(true);
        allIn1Box.setText("только в одном купе ");
        allIn1Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allIn1BoxActionPerformed(evt);
            }
        });

        lateralDisableBox.setSelected(true);
        lateralDisableBox.setText("запретить боковые");

        cupePriorityBox.setSelected(true);
        cupePriorityBox.setText("Приоритет номера купе");

        jLabel2.setText("Группа");

        groupBox1.setEditable(false);
        groupBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        groupBox1.setText("1");
        groupBox1.setEnabled(false);

        groupBox2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        groupBox3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        groupBox4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        groupBox5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        groupBox6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        childBox1.setText("Детский");
        childBox1.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator5)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(83, 83, 83)
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                                .addComponent(jLabel2))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(passenger1)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(surName1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(surName2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(surName3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(surName4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(surName5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(surName6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addComponent(passenger5)
                                                        .addComponent(passenger4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(passenger3)
                                                        .addComponent(passenger2))
                                                .addGap(16, 16, 16)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(name1)
                                                        .addComponent(name2)
                                                        .addComponent(name3)
                                                        .addComponent(name4)
                                                        .addComponent(name5)
                                                        .addComponent(name6))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(groupBox5, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(groupBox4, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(groupBox3, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(groupBox2, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(groupBox1, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(groupBox6))
                                                .addGap(7, 7, 7))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(allIn1Box)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addComponent(passenger6)
                                                                                .addGap(18, 18, 18)
                                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(childBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(childBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(childBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(childBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(childBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                        .addComponent(childBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(lowSeatBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(lowSeatBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(lowSeatBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(lowSeatBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(lowSeatBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(lowSeatBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                .addComponent(cupePriorityBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(lateralDisableBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel2))
                                                .addGap(18, 18, 18)
                                                .addComponent(passenger1))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(surName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(groupBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lowSeatBox1)
                                        .addComponent(childBox1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(passenger2)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(surName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(name2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(groupBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(childBox2)
                                        .addComponent(lowSeatBox2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(passenger3)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(surName3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(name3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(groupBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(childBox3)
                                        .addComponent(lowSeatBox3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(surName4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(name4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(groupBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(passenger4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(childBox4)
                                        .addComponent(lowSeatBox4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(passenger5)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(surName5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(name5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(groupBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(childBox5, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lowSeatBox5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(surName6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(name6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(groupBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(passenger6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(childBox6)
                                        .addComponent(lowSeatBox6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(allIn1Box)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lateralDisableBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cupePriorityBox)
                                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(365, 365, 365)
                                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(321, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
                                        .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        if (startButton.getText().equals("Start")) {
            if (dayBox.getSelectedIndex() != 0 && monthBox.getSelectedIndex() != 0) {
                startButton.setText("Stop");
                drive = new Drive(this);
                new Thread(drive).start();
            } else {
                print("Выберите дату отправления!\n");
            }
        } else {
            startButton.setText("Start");
            drive.getWebDriver().close();
        }
    }//GEN-LAST:event_startButtonActionPerformed

    private void anyTrainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anyTrainButtonActionPerformed
        trainNumberField.setEnabled(!anyTrainButton.isSelected());
    }//GEN-LAST:event_anyTrainButtonActionPerformed

    private void specifyTrainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specifyTrainButtonActionPerformed
        trainNumberField.setEnabled(specifyTrainButton.isSelected());
    }//GEN-LAST:event_specifyTrainButtonActionPerformed

    private void passenger2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passenger2ActionPerformed
        enablePassenger(1);
    }//GEN-LAST:event_passenger2ActionPerformed

    private void changeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeButtonActionPerformed
        String buffer = fromField.getText();
        fromField.setText(tillField.getText());
        tillField.setText(buffer);
    }//GEN-LAST:event_changeButtonActionPerformed

    public void print(String text) {
        jTextArea1.setText(jTextArea1.getText() + text);
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }

    public void println(String text) {
        print(text + "\n");
    }

    private void passenger3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passenger3ActionPerformed
        enablePassenger(2);
    }//GEN-LAST:event_passenger3ActionPerformed

    private void passenger5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passenger5ActionPerformed
        enablePassenger(4);
    }//GEN-LAST:event_passenger5ActionPerformed

    private void passenger4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passenger4ActionPerformed
        enablePassenger(3);
    }//GEN-LAST:event_passenger4ActionPerformed

    private void passenger6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passenger6ActionPerformed
        enablePassenger(5);
    }//GEN-LAST:event_passenger6ActionPerformed

    private void plazkartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plazkartButtonActionPerformed
        lateralDisableBox.setEnabled(plazkartButton.isSelected());
    }//GEN-LAST:event_plazkartButtonActionPerformed

    private void cupeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cupeButtonActionPerformed
        lateralDisableBox.setEnabled(plazkartButton.isSelected());
    }//GEN-LAST:event_cupeButtonActionPerformed

    private void luxButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luxButtonActionPerformed
        lateralDisableBox.setEnabled(plazkartButton.isSelected());
    }//GEN-LAST:event_luxButtonActionPerformed

    private void allIn1BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allIn1BoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allIn1BoxActionPerformed

    private void fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldFocusGained
        JTextField a = (JTextField) (evt.getSource());
        a.selectAll();
    }//GEN-LAST:event_fieldFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }

    String getFromStation() {
        return fromField.getText();
    }

    String getTillStation() {
        return tillField.getText();
    }

    int[] getDate() {
        return new int[]{dayBox.getSelectedIndex(), monthBox.getSelectedIndex()};
    }

    String getTrainNumberField() {
        return trainNumberField.getText();
    }

    String getWagonType() {
        if (plazkartButton.isSelected())
            return "Плацкарт";
        else if (cupeButton.isSelected())
            return "Купе";
        else return "Люкс";
    }

    int getPassangerNumber() {
        int counter = 0;
        for (JCheckBox box : passengerArray)
            if (box.isSelected())
                counter++;
        return counter;
    }

    int getCupeSize() {
        if (plazkartButton.isSelected()) {
            if (lateralDisableBox.isSelected())
                return 4;
            return 6;
        } else if (cupeButton.isSelected())
            return 4;
        else return 2;
    }

    protected boolean isConcreteTrainNumber() {
        return !anyTrainButton.isSelected();
    }

    protected String getLogin() {
        return usernameField.getText();
    }

    protected String getPassword() {
        return passwordField.getText();
    }

    private void enablePassenger(int num) {
        boolean passSelected = passengerArray[num].isSelected();
        surNameArray[num].setEnabled(passSelected);
        nameArray[num].setEnabled(passSelected);
        childBoxArray[num].setEnabled(passSelected);
        lowSeatArray[num].setEnabled(passSelected);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JCheckBox allIn1Box;
    protected javax.swing.JRadioButton anyTrainButton;
    javax.swing.JCheckBox authorizeBox;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton changeButton;
    protected javax.swing.JCheckBox childBox1;
    protected javax.swing.JCheckBox childBox2;
    protected javax.swing.JCheckBox childBox3;
    protected javax.swing.JCheckBox childBox4;
    protected javax.swing.JCheckBox childBox5;
    protected javax.swing.JCheckBox childBox6;
    protected javax.swing.JRadioButton cupeButton;
    private javax.swing.JCheckBox cupePriorityBox;
    private javax.swing.JLabel dateLabel;
    protected javax.swing.JComboBox<String> dayBox;
    javax.swing.JTextField fromField;
    private javax.swing.JTextField groupBox1;
    private javax.swing.JTextField groupBox2;
    private javax.swing.JTextField groupBox3;
    private javax.swing.JTextField groupBox4;
    private javax.swing.JTextField groupBox5;
    private javax.swing.JTextField groupBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFrom;
    private javax.swing.JLabel jLabelTill;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextArea jTextArea1;
    protected javax.swing.JCheckBox lateralDisableBox;
    private javax.swing.JLabel loginLabel;
    protected javax.swing.JCheckBox lowSeatBox1;
    protected javax.swing.JCheckBox lowSeatBox2;
    protected javax.swing.JCheckBox lowSeatBox3;
    protected javax.swing.JCheckBox lowSeatBox4;
    protected javax.swing.JCheckBox lowSeatBox5;
    protected javax.swing.JCheckBox lowSeatBox6;
    protected javax.swing.JRadioButton luxButton;
    protected javax.swing.JComboBox<String> monthBox;
    protected javax.swing.JTextField name1;
    protected javax.swing.JTextField name2;
    protected javax.swing.JTextField name3;
    protected javax.swing.JTextField name4;
    protected javax.swing.JTextField name5;
    protected javax.swing.JTextField name6;
    private javax.swing.JLabel numTrainLabel;
    private javax.swing.JCheckBox passenger1;
    protected javax.swing.JCheckBox passenger2;
    protected javax.swing.JCheckBox passenger3;
    protected javax.swing.JCheckBox passenger4;
    protected javax.swing.JCheckBox passenger5;
    protected javax.swing.JCheckBox passenger6;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    protected javax.swing.JRadioButton plazkartButton;
    protected javax.swing.JRadioButton specifyTrainButton;
    private javax.swing.JButton startButton;
    protected javax.swing.JTextField surName1;
    protected javax.swing.JTextField surName2;
    protected javax.swing.JTextField surName3;
    protected javax.swing.JTextField surName4;
    protected javax.swing.JTextField surName5;
    protected javax.swing.JTextField surName6;
    protected javax.swing.JTextField tillField;
    protected javax.swing.JTextField trainNumberField;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel wagonType;
    // End of variables declaration//GEN-END:variables
    private Drive drive;
    private JCheckBox[] passengerArray;
    JTextField[] surNameArray;
    JTextField[] nameArray;
    JCheckBox[] lowSeatArray;
    JCheckBox[] childBoxArray;
    JTextField[] groupArray;

    private void initUserComponents() {
        JCheckBox[] passengerArray = {passenger1, passenger2, passenger3, passenger4, passenger5, passenger6};
        JCheckBox[] lowSeatArray = {lowSeatBox1, lowSeatBox2, lowSeatBox3, lowSeatBox4, lowSeatBox5, lowSeatBox6};
        JCheckBox[] childBoxArray = {childBox1, childBox2, childBox3, childBox4, childBox5, childBox6};
        JTextField[] surNameArray = {surName1, surName2, surName3, surName4, surName5, surName6};
        JTextField[] nameArray = {name1, name2, name3, name4, name5, name6};
        JTextField[] groupArray = {groupBox1, groupBox2, groupBox3, groupBox4, groupBox5, groupBox6};
        this.passengerArray = passengerArray;
        this.surNameArray = surNameArray;
        this.nameArray = nameArray;
        this.lowSeatArray = lowSeatArray;
        this.childBoxArray = childBoxArray;
        this.groupArray = groupArray;
    }

    int getOrderLowSeatNum(int start, int stop) {
        int counter = 0;
        for (int i = start; i < stop; i++) {
            if (lowSeatArray[i].isSelected())
                counter++;
        }
        return counter;
    }
}
